package com.luv2read.springbootlibrary.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseSchemaFixer {

    private static final Logger log = LoggerFactory.getLogger(DatabaseSchemaFixer.class);

    private final JdbcTemplate jdbcTemplate;

    public DatabaseSchemaFixer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void fixColumnTypes() {
        // Fix messages.closed: MySQL tinyint(1) migrated to smallint/integer in PostgreSQL
        // Hibernate tries to ALTER to boolean without USING clause — fix it here with CAST
        try {
            jdbcTemplate.execute(
                "ALTER TABLE messages ALTER COLUMN closed TYPE boolean USING closed != 0"
            );
            log.info("Fixed messages.closed column type to boolean");
        } catch (Exception e) {
            log.debug("messages.closed already boolean or error: {}", e.getMessage());
        }

        // Fix review.date: may be incompatible type from MySQL migration
        // Hibernate tries to ALTER to timestamp(6) without USING clause
        try {
            jdbcTemplate.execute(
                "ALTER TABLE review ALTER COLUMN date TYPE timestamp(6) without time zone USING date::timestamp(6) without time zone"
            );
            log.info("Fixed review.date column type to timestamp");
        } catch (Exception e) {
            log.debug("review.date already timestamp or error: {}", e.getMessage());
        }
    }

    @EventListener(ApplicationReadyEvent.class)
    public void fixSequences() {
        // All entities use GenerationType.IDENTITY. MySQL AUTO_INCREMENT doesn't migrate
        // to PostgreSQL — the id columns are plain bigint with no sequence/default.
        // Fix by creating a sequence and setting it as the column default.
        for (String table : new String[]{"book", "checkout", "history", "messages", "review", "app_user"}) {
            fixSequenceForTable(table);
        }
    }

    private void fixSequenceForTable(String tableName) {
        String quotedTable = "\"" + tableName + "\"";
        try {
            var rows = jdbcTemplate.queryForList(
                "SELECT is_identity FROM information_schema.columns " +
                "WHERE table_schema = current_schema() AND table_name = ? AND column_name = 'id'",
                tableName
            );
            if (rows.isEmpty()) {
                log.debug("Table {} not found in current schema, skipping", tableName);
                return;
            }
            String isIdentity = (String) rows.get(0).get("is_identity");
            Long maxId = jdbcTemplate.queryForObject(
                "SELECT COALESCE(MAX(id), 0) FROM " + quotedTable, Long.class
            );
            long startWith = (maxId == null ? 0L : maxId) + 1;

            if ("YES".equals(isIdentity)) {
                // Already a PostgreSQL IDENTITY column — restart the sequence past existing data
                if (maxId != null && maxId > 0) {
                    jdbcTemplate.execute("ALTER TABLE " + quotedTable + " ALTER COLUMN id RESTART WITH " + startWith);
                    log.info("Restarted IDENTITY sequence for {}.id at {}", tableName, startWith);
                } else {
                    log.debug("{}.id is already IDENTITY with no data, no restart needed", tableName);
                }
                return;
            }

            // Plain bigint (from MySQL migration) — convert to PostgreSQL IDENTITY so Hibernate
            // stops dropping our nextval default on every restart.
            // DROP DEFAULT first (safe no-op if no default exists).
            jdbcTemplate.execute("ALTER TABLE " + quotedTable + " ALTER COLUMN id DROP DEFAULT");
            jdbcTemplate.execute(
                "ALTER TABLE " + quotedTable + " ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH " + startWith + ")"
            );
            log.info("Converted {}.id to IDENTITY column (start: {})", tableName, startWith);
        } catch (Exception e) {
            log.warn("Could not fix identity for {}.id: {}", tableName, e.getMessage());
        }
    }

    @EventListener(ApplicationReadyEvent.class)
    public void fixHistoryTableSchema() {
        // Check which table name exists (case-sensitive on Linux MySQL)
        String tableName = findHistoryTableName();
        if (tableName == null) {
            log.warn("History table not found - Hibernate ddl-auto should create it");
            return;
        }

        log.info("Found history table as: '{}'", tableName);

        // Fix column types
        try {
            jdbcTemplate.execute("ALTER TABLE history ALTER COLUMN description TYPE TEXT");
            jdbcTemplate.execute("ALTER TABLE history ALTER COLUMN img TYPE TEXT");
            log.info("History table columns verified/updated successfully");
        } catch (Exception e) {
            log.warn("Could not alter History table columns (may already be correct): {}", e.getMessage());
        }
    }

    private String findHistoryTableName() {
        try {
            var tables = jdbcTemplate.queryForList(
                "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = current_schema() AND TABLE_NAME = 'history'"
            );
            if (!tables.isEmpty()) {
                return (String) tables.get(0).get("TABLE_NAME");
            }
        } catch (Exception e) {
            log.warn("Could not query for History table: {}", e.getMessage());
        }
        return null;
    }
}
